# CMake generated Testfile for 
# Source directory: /home/eirikr/Github/silksurf
# Build directory: /home/eirikr/Github/silksurf/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(css_tokenizer "/home/eirikr/Github/silksurf/build-asan/test_css_tokenizer")
set_tests_properties(css_tokenizer PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;375;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_parser "/home/eirikr/Github/silksurf/build-asan/test_css_parser")
set_tests_properties(css_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;376;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(full_pipeline "/home/eirikr/Github/silksurf/build-asan/test_full_pipeline")
set_tests_properties(full_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;377;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(parser_basic "/home/eirikr/Github/silksurf/build-asan/test_parser_basic")
set_tests_properties(parser_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;378;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(dom_parsing "/home/eirikr/Github/silksurf/build-asan/test_dom_parsing")
set_tests_properties(dom_parsing PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;379;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_engine "/home/eirikr/Github/silksurf/build-asan/test_css_engine")
set_tests_properties(css_engine PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;380;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_cascade "/home/eirikr/Github/silksurf/build-asan/test_css_cascade")
set_tests_properties(css_cascade PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;381;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_cascade_native "/home/eirikr/Github/silksurf/build-asan/test_css_cascade_native")
set_tests_properties(css_cascade_native PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;382;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_cascade_integration "/home/eirikr/Github/silksurf/build-asan/test_css_cascade_integration")
set_tests_properties(css_cascade_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;383;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_selector_matching "/home/eirikr/Github/silksurf/build-asan/test_css_selector_matching")
set_tests_properties(css_selector_matching PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;384;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(css_native_pipeline "/home/eirikr/Github/silksurf/build-asan/test_css_native_pipeline")
set_tests_properties(css_native_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;385;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(simd_detection "/home/eirikr/Github/silksurf/build-asan/test_simd_detection")
set_tests_properties(simd_detection PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;386;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(e2e_rendering "/home/eirikr/Github/silksurf/build-asan/test_e2e_rendering")
set_tests_properties(e2e_rendering PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;387;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(inline_layout "/home/eirikr/Github/silksurf/build-asan/test_inline_layout")
set_tests_properties(inline_layout PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;388;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(replaced_elements "/home/eirikr/Github/silksurf/build-asan/test_replaced_elements")
set_tests_properties(replaced_elements PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;389;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
add_test(xcb_shm "/home/eirikr/Github/silksurf/build-asan/test_xcb_shm")
set_tests_properties(xcb_shm PROPERTIES  _BACKTRACE_TRIPLES "/home/eirikr/Github/silksurf/CMakeLists.txt;390;add_test;/home/eirikr/Github/silksurf/CMakeLists.txt;0;")
