/*
 * Date and time formatting data for Intl.DateTimeFormat, generated by
 * scripts/gen_intl_datetime_data.mjs from the reference ECMA-402
 * implementation's own output; see docs/design/ARCHITECTURE-DECISIONS.md
 * AD-033 for why the table is enumerated rather than derived.
 *
 * PATTERNS holds every distinct pattern once, one per line. DATE_PATTERNS
 * indexes it by a dense signature over the five date field widths and
 * TIME_PATTERNS by a dense signature over the three time field widths and the
 * hour cycle, so a lookup is one array read and carries no matching step.
 *
 * The data derives from the Unicode Common Locale Data Repository and carries
 * the Unicode license recorded in NOTICE-CLDR.
 */

/// Signature slot no pattern occupies. Every combination an option bag can
/// reach carries a pattern; the empty slots are signatures no request
/// produces -- the empty field set, and the hour cycle variants of a time
/// signature that names no hour -- and formatting reports a reached one
/// rather than rendering an empty string.
pub(super) const NONE: u16 = u16::MAX;

/// Every distinct pattern, one per line, shared across locales.
pub(super) const PATTERNS: &str = "\
d
dd
M
M/d
M/dd
MM
MM/d
MM/dd
MMMM
MMMM d
MMMM dd
MMM
MMM d
MMM dd
MMMMM
MMMMM d
MMMMM dd
y
y' (day: 'd)
y' (day: 'dd)
M/y
M/d/y
M/dd/y
MM/y
MM/d/y
MM/dd/y
MMMM y
MMMM d, y
MMMM dd, y
MMM y
MMM d, y
MMM dd, y
MMMMM y
MMMMM d, y
MMMMM dd, y
yy
d yy
yy' (day: 'dd)
M/yy
M/d/yy
M/dd/yy
MM/yy
MM/d/yy
MM/dd/yy
MMMM yy
MMMM d, yy
MMMM dd, yy
MMM yy
MMM d, yy
MMM dd, yy
MMMMM yy
MMMMM d, yy
MMMMM dd, yy
M/d/y GGGG
d GGGG
GGGG' (day: 'dd)
M GGGG
M/d GGGG
M/dd GGGG
GGGG' (month: 'MM)
MM/d GGGG
MM/dd GGGG
GGGG' (month: 'MMMM)
MMMM d GGGG
MMMM dd GGGG
MMM GGGG
MMM d GGGG
MMM dd GGGG
GGGG' (month: 'MMMMM)
MMMMM d GGGG
MMMMM dd GGGG
y GGGG
y GGGG' (day: 'd)
y GGGG' (day: 'dd)
M/y GGGG
M/dd/y GGGG
MM/y GGGG
MM/d/y GGGG
MM/dd/y GGGG
MMMM y GGGG
MMMM d, y GGGG
MMMM dd, y GGGG
MMM y GGGG
MMM d, y GGGG
MMM dd, y GGGG
MMMMM y GGGG
MMMMM d, y GGGG
MMMMM dd, y GGGG
yy GGGG
yy GGGG' (day: 'd)
yy GGGG' (day: 'dd)
M/yy GGGG
M/d/yy GGGG
M/dd/yy GGGG
MM/yy GGGG
MM/d/yy GGGG
MM/dd/yy GGGG
MMMM yy GGGG
MMMM d, yy GGGG
MMMM dd, yy GGGG
MMM yy GGGG
MMM d, yy GGGG
MMM dd, yy GGGG
MMMMM yy GGGG
MMMMM d, yy GGGG
MMMMM dd, yy GGGG
M/d/y G
G' (day: 'd)
G' (day: 'dd)
G' (month: 'M)
M/d G
M/dd G
G' (month: 'MM)
MM/d G
MM/dd G
G' (month: 'MMMM)
MMMM d G
MMMM dd G
G' (month: 'MMM)
MMM d G
MMM dd G
G' (month: 'MMMMM)
MMMMM d G
MMMMM dd G
y G
y G' (day: 'd)
y G' (day: 'dd)
M/y G
M/dd/y G
MM/y G
MM/d/y G
MM/dd/y G
MMMM y G
MMMM d, y G
MMMM dd, y G
MMM y G
MMM d, y G
MMM dd, y G
MMMMM y G
MMMMM d, y G
MMMMM dd, y G
yy G
yy G' (day: 'd)
yy G' (day: 'dd)
M/yy G
M/d/yy G
M/dd/yy G
MM/yy G
MM/d/yy G
MM/dd/yy G
MMMM yy G
MMMM d, yy G
MMMM dd, yy G
MMM yy G
MMM d, yy G
MMM dd, yy G
MMMMM yy G
MMMMM d, yy G
MMMMM dd, yy G
M/d/y GGGGG
d GGGGG
dd GGGGG
M GGGGG
M/d GGGGG
M/dd GGGGG
MM GGGGG
MM/d GGGGG
MM/dd GGGGG
MMMM GGGGG
MMMM d GGGGG
MMMM dd GGGGG
MMM GGGGG
MMM d GGGGG
MMM dd GGGGG
GGGGG' (month: 'MMMMM)
MMMMM d GGGGG
MMMMM dd GGGGG
y GGGGG
y GGGGG' (day: 'd)
y GGGGG' (day: 'dd)
M/y GGGGG
M/dd/y GGGGG
MM/y GGGGG
MM/d/y GGGGG
MM/dd/y GGGGG
MMMM y GGGGG
MMMM d, y GGGGG
MMMM dd, y GGGGG
MMM y GGGGG
MMM d, y GGGGG
MMM dd, y GGGGG
MMMMM y GGGGG
MMMMM d, y GGGGG
MMMMM dd, y GGGGG
yy GGGGG
yy GGGGG' (day: 'd)
yy GGGGG' (day: 'dd)
M/yy GGGGG
M/d/yy GGGGG
M/dd/yy GGGGG
MM/yy GGGGG
MM/d/yy GGGGG
MM/dd/yy GGGGG
MMMM yy GGGGG
MMMM d, yy GGGGG
MMMM dd, yy GGGGG
MMM yy GGGGG
MMM d, yy GGGGG
MMM dd, yy GGGGG
MMMMM yy GGGGG
MMMMM d, yy GGGGG
MMMMM dd, yy GGGGG
EEEE
d EEEE
dd EEEE
M EEEE
EEEE, M/d
EEEE, M/dd
MM EEEE
EEEE, MM/d
EEEE, MM/dd
MMMM EEEE
EEEE, MMMM d
EEEE, MMMM dd
MMM EEEE
EEEE, MMM d
EEEE, MMM dd
EEEE' (month: 'MMMMM)
EEEE, MMMMM d
EEEE, MMMMM dd
y EEEE
d EEEE y
dd EEEE y
M/y EEEE
EEEE, M/d/y
EEEE, M/dd/y
MM/y EEEE
EEEE, MM/d/y
EEEE, MM/dd/y
MMMM y EEEE
EEEE, MMMM d, y
EEEE, MMMM dd, y
MMM y EEEE
EEEE, MMM d, y
EEEE, MMM dd, y
MMMMM y EEEE
EEEE, MMMMM d, y
EEEE, MMMMM dd, y
yy EEEE
d EEEE yy
dd EEEE yy
M/yy EEEE
EEEE, M/d/yy
EEEE, M/dd/yy
MM/yy EEEE
EEEE, MM/d/yy
EEEE, MM/dd/yy
MMMM yy EEEE
EEEE, MMMM d, yy
EEEE, MMMM dd, yy
MMM yy EEEE
EEEE, MMM d, yy
EEEE, MMM dd, yy
MMMMM yy EEEE
EEEE, MMMMM d, yy
EEEE, MMMMM dd, yy
GGGG EEEE
d EEEE GGGG
dd EEEE GGGG
EEEE, M/d GGGG
EEEE, M/dd GGGG
EEEE, MM/d GGGG
EEEE, MM/dd GGGG
EEEE, MMMM d GGGG
EEEE, MMMM dd GGGG
EEEE, MMM d GGGG
EEEE, MMM dd GGGG
EEEE, MMMMM d GGGG
EEEE, MMMMM dd GGGG
y GGGG EEEE
y GGGG' (day: 'd EEEE)
y GGGG' (day: 'dd EEEE)
M/y GGGG EEEE
EEEE, M/d/y GGGG
EEEE, M/dd/y GGGG
MM/y GGGG EEEE
EEEE, MM/d/y GGGG
EEEE, MM/dd/y GGGG
MMMM y GGGG EEEE
EEEE, MMMM d, y GGGG
EEEE, MMMM dd, y GGGG
MMM y GGGG EEEE
EEEE, MMM d, y GGGG
EEEE, MMM dd, y GGGG
MMMMM y GGGG EEEE
EEEE, MMMMM d, y GGGG
EEEE, MMMMM dd, y GGGG
yy GGGG EEEE
d EEEE yy GGGG
yy GGGG' (day: 'dd EEEE)
M/yy GGGG EEEE
EEEE, M/d/yy GGGG
EEEE, M/dd/yy GGGG
MM/yy GGGG EEEE
EEEE, MM/d/yy GGGG
EEEE, MM/dd/yy GGGG
MMMM yy GGGG EEEE
EEEE, MMMM d, yy GGGG
EEEE, MMMM dd, yy GGGG
MMM yy GGGG EEEE
EEEE, MMM d, yy GGGG
EEEE, MMM dd, yy GGGG
MMMMM yy GGGG EEEE
EEEE, MMMMM d, yy GGGG
EEEE, MMMMM dd, yy GGGG
G EEEE
d EEEE G
dd EEEE G
EEEE, M/d G
EEEE, M/dd G
EEEE, MM/d G
EEEE, MM/dd G
EEEE, MMMM d G
EEEE, MMMM dd G
EEEE, MMM d G
EEEE, MMM dd G
EEEE, MMMMM d G
EEEE, MMMMM dd G
y G EEEE
y G' (day: 'd EEEE)
y G' (day: 'dd EEEE)
M/y G EEEE
EEEE, M/d/y G
EEEE, M/dd/y G
MM/y G EEEE
EEEE, MM/d/y G
EEEE, MM/dd/y G
MMMM y G EEEE
EEEE, MMMM d, y G
EEEE, MMMM dd, y G
MMM y G EEEE
EEEE, MMM d, y G
EEEE, MMM dd, y G
MMMMM y G EEEE
EEEE, MMMMM d, y G
EEEE, MMMMM dd, y G
yy G EEEE
yy G' (day: 'd EEEE)
yy G' (day: 'dd EEEE)
M/yy G EEEE
EEEE, M/d/yy G
EEEE, M/dd/yy G
MM/yy G EEEE
EEEE, MM/d/yy G
EEEE, MM/dd/yy G
MMMM yy G EEEE
EEEE, MMMM d, yy G
EEEE, MMMM dd, yy G
MMM yy G EEEE
EEEE, MMM d, yy G
EEEE, MMM dd, yy G
MMMMM yy G EEEE
EEEE, MMMMM d, yy G
EEEE, MMMMM dd, yy G
EEEE GGGGG
d EEEE GGGGG
dd EEEE GGGGG
EEEE, M/d GGGGG
EEEE, M/dd GGGGG
EEEE, MM/d GGGGG
EEEE, MM/dd GGGGG
EEEE, MMMM d GGGGG
EEEE, MMMM dd GGGGG
EEEE, MMM d GGGGG
EEEE, MMM dd GGGGG
EEEE, MMMMM d GGGGG
EEEE, MMMMM dd GGGGG
y GGGGG EEEE
d EEEE y GGGGG
y GGGGG' (day: 'dd EEEE)
M/y GGGGG EEEE
EEEE, M/d/y GGGGG
EEEE, M/dd/y GGGGG
MM/y GGGGG EEEE
EEEE, MM/d/y GGGGG
EEEE, MM/dd/y GGGGG
MMMM y GGGGG EEEE
EEEE, MMMM d, y GGGGG
EEEE, MMMM dd, y GGGGG
MMM y GGGGG EEEE
EEEE, MMM d, y GGGGG
EEEE, MMM dd, y GGGGG
MMMMM y GGGGG EEEE
EEEE, MMMMM d, y GGGGG
EEEE, MMMMM dd, y GGGGG
yy GGGGG EEEE
d EEEE yy GGGGG
dd EEEE yy GGGGG
M/yy GGGGG EEEE
EEEE, M/d/yy GGGGG
EEEE, M/dd/yy GGGGG
MM/yy GGGGG EEEE
EEEE, MM/d/yy GGGGG
EEEE, MM/dd/yy GGGGG
MMMM yy GGGGG EEEE
EEEE, MMMM d, yy GGGGG
EEEE, MMMM dd, yy GGGGG
MMM yy GGGGG EEEE
EEEE, MMM d, yy GGGGG
EEEE, MMM dd, yy GGGGG
MMMMM yy GGGGG EEEE
EEEE, MMMMM d, yy GGGGG
EEEE, MMMMM dd, yy GGGGG
EEE
d EEE
dd EEE
M EEE
EEE, M/d
EEE, M/dd
EEE' (month: 'MM)
EEE, MM/d
EEE, MM/dd
EEE' (month: 'MMMM)
EEE, MMMM d
EEE, MMMM dd
MMM EEE
EEE, MMM d
EEE, MMM dd
EEE' (month: 'MMMMM)
EEE, MMMMM d
EEE, MMMMM dd
y EEE
d EEE y
dd EEE y
M/y EEE
EEE, M/d/y
EEE, M/dd/y
MM/y EEE
EEE, MM/d/y
EEE, MM/dd/y
MMMM y EEE
EEE, MMMM d, y
EEE, MMMM dd, y
MMM y EEE
EEE, MMM d, y
EEE, MMM dd, y
MMMMM y EEE
EEE, MMMMM d, y
EEE, MMMMM dd, y
EEE yy
d EEE yy
dd EEE yy
M/yy EEE
EEE, M/d/yy
EEE, M/dd/yy
MM/yy EEE
EEE, MM/d/yy
EEE, MM/dd/yy
MMMM yy EEE
EEE, MMMM d, yy
EEE, MMMM dd, yy
MMM yy EEE
EEE, MMM d, yy
EEE, MMM dd, yy
MMMMM yy EEE
EEE, MMMMM d, yy
EEE, MMMMM dd, yy
EEE GGGG
d EEE GGGG
dd EEE GGGG
EEE, M/d GGGG
EEE, M/dd GGGG
EEE, MM/d GGGG
EEE, MM/dd GGGG
EEE, MMMM d GGGG
EEE, MMMM dd GGGG
EEE, MMM d GGGG
EEE, MMM dd GGGG
EEE, MMMMM d GGGG
EEE, MMMMM dd GGGG
y GGGG EEE
d EEE y GGGG
y GGGG' (day: 'dd EEE)
M/y GGGG EEE
EEE, M/d/y GGGG
EEE, M/dd/y GGGG
MM/y GGGG EEE
EEE, MM/d/y GGGG
EEE, MM/dd/y GGGG
MMMM y GGGG EEE
EEE, MMMM d, y GGGG
EEE, MMMM dd, y GGGG
MMM y GGGG EEE
EEE, MMM d, y GGGG
EEE, MMM dd, y GGGG
MMMMM y GGGG EEE
EEE, MMMMM d, y GGGG
EEE, MMMMM dd, y GGGG
yy GGGG EEE
d EEE yy GGGG
dd EEE yy GGGG
M/yy GGGG EEE
EEE, M/d/yy GGGG
EEE, M/dd/yy GGGG
MM/yy GGGG EEE
EEE, MM/d/yy GGGG
EEE, MM/dd/yy GGGG
MMMM yy GGGG EEE
EEE, MMMM d, yy GGGG
EEE, MMMM dd, yy GGGG
MMM yy GGGG EEE
EEE, MMM d, yy GGGG
EEE, MMM dd, yy GGGG
MMMMM yy GGGG EEE
EEE, MMMMM d, yy GGGG
EEE, MMMMM dd, yy GGGG
G EEE
d EEE G
dd EEE G
EEE, M/d G
EEE, M/dd G
EEE, MM/d G
EEE, MM/dd G
EEE, MMMM d G
EEE, MMMM dd G
EEE, MMM d G
EEE, MMM dd G
EEE, MMMMM d G
EEE, MMMMM dd G
y G EEE
y G' (day: 'd EEE)
y G' (day: 'dd EEE)
M/y G EEE
EEE, M/d/y G
EEE, M/dd/y G
MM/y G EEE
EEE, MM/d/y G
EEE, MM/dd/y G
MMMM y G EEE
EEE, MMMM d, y G
EEE, MMMM dd, y G
MMM y G EEE
EEE, MMM d, y G
EEE, MMM dd, y G
MMMMM y G EEE
EEE, MMMMM d, y G
EEE, MMMMM dd, y G
yy G EEE
d EEE yy G
yy G' (day: 'dd EEE)
M/yy G EEE
EEE, M/d/yy G
EEE, M/dd/yy G
MM/yy G EEE
EEE, MM/d/yy G
EEE, MM/dd/yy G
MMMM yy G EEE
EEE, MMMM d, yy G
EEE, MMMM dd, yy G
MMM yy G EEE
EEE, MMM d, yy G
EEE, MMM dd, yy G
MMMMM yy G EEE
EEE, MMMMM d, yy G
EEE, MMMMM dd, yy G
EEE GGGGG
d EEE GGGGG
dd EEE GGGGG
EEE, M/d GGGGG
EEE, M/dd GGGGG
EEE, MM/d GGGGG
EEE, MM/dd GGGGG
EEE, MMMM d GGGGG
EEE, MMMM dd GGGGG
EEE, MMM d GGGGG
EEE, MMM dd GGGGG
EEE, MMMMM d GGGGG
EEE, MMMMM dd GGGGG
y GGGGG EEE
d EEE y GGGGG
dd EEE y GGGGG
M/y GGGGG EEE
EEE, M/d/y GGGGG
EEE, M/dd/y GGGGG
MM/y GGGGG EEE
EEE, MM/d/y GGGGG
EEE, MM/dd/y GGGGG
MMMM y GGGGG EEE
EEE, MMMM d, y GGGGG
EEE, MMMM dd, y GGGGG
MMM y GGGGG EEE
EEE, MMM d, y GGGGG
EEE, MMM dd, y GGGGG
MMMMM y GGGGG EEE
EEE, MMMMM d, y GGGGG
EEE, MMMMM dd, y GGGGG
yy GGGGG EEE
d EEE yy GGGGG
dd EEE yy GGGGG
M/yy GGGGG EEE
EEE, M/d/yy GGGGG
EEE, M/dd/yy GGGGG
MM/yy GGGGG EEE
EEE, MM/d/yy GGGGG
EEE, MM/dd/yy GGGGG
MMMM yy GGGGG EEE
EEE, MMMM d, yy GGGGG
EEE, MMMM dd, yy GGGGG
MMM yy GGGGG EEE
EEE, MMM d, yy GGGGG
EEE, MMM dd, yy GGGGG
MMMMM yy GGGGG EEE
EEE, MMMMM d, yy GGGGG
EEE, MMMMM dd, yy GGGGG
EEEEE
d EEEEE
dd EEEEE
M EEEEE
EEEEE, M/d
EEEEE, M/dd
MM EEEEE
EEEEE, MM/d
EEEEE, MM/dd
MMMM EEEEE
EEEEE, MMMM d
EEEEE, MMMM dd
MMM EEEEE
EEEEE, MMM d
EEEEE, MMM dd
MMMMM EEEEE
EEEEE, MMMMM d
EEEEE, MMMMM dd
y EEEEE
d EEEEE y
dd EEEEE y
M/y EEEEE
EEEEE, M/d/y
EEEEE, M/dd/y
MM/y EEEEE
EEEEE, MM/d/y
EEEEE, MM/dd/y
MMMM y EEEEE
EEEEE, MMMM d, y
EEEEE, MMMM dd, y
MMM y EEEEE
EEEEE, MMM d, y
EEEEE, MMM dd, y
MMMMM y EEEEE
EEEEE, MMMMM d, y
EEEEE, MMMMM dd, y
yy EEEEE
d EEEEE yy
dd EEEEE yy
M/yy EEEEE
EEEEE, M/d/yy
EEEEE, M/dd/yy
MM/yy EEEEE
EEEEE, MM/d/yy
EEEEE, MM/dd/yy
MMMM yy EEEEE
EEEEE, MMMM d, yy
EEEEE, MMMM dd, yy
MMM yy EEEEE
EEEEE, MMM d, yy
EEEEE, MMM dd, yy
MMMMM yy EEEEE
EEEEE, MMMMM d, yy
EEEEE, MMMMM dd, yy
GGGG EEEEE
d EEEEE GGGG
dd EEEEE GGGG
EEEEE, M/d GGGG
EEEEE, M/dd GGGG
EEEEE, MM/d GGGG
EEEEE, MM/dd GGGG
EEEEE, MMMM d GGGG
EEEEE, MMMM dd GGGG
EEEEE, MMM d GGGG
EEEEE, MMM dd GGGG
EEEEE, MMMMM d GGGG
EEEEE, MMMMM dd GGGG
y GGGG EEEEE
y GGGG' (day: 'd EEEEE)
y GGGG' (day: 'dd EEEEE)
M/y GGGG EEEEE
EEEEE, M/d/y GGGG
EEEEE, M/dd/y GGGG
MM/y GGGG EEEEE
EEEEE, MM/d/y GGGG
EEEEE, MM/dd/y GGGG
MMMM y GGGG EEEEE
EEEEE, MMMM d, y GGGG
EEEEE, MMMM dd, y GGGG
MMM y GGGG EEEEE
EEEEE, MMM d, y GGGG
EEEEE, MMM dd, y GGGG
MMMMM y GGGG EEEEE
EEEEE, MMMMM d, y GGGG
EEEEE, MMMMM dd, y GGGG
yy GGGG EEEEE
yy GGGG' (day: 'd EEEEE)
yy GGGG' (day: 'dd EEEEE)
M/yy GGGG EEEEE
EEEEE, M/d/yy GGGG
EEEEE, M/dd/yy GGGG
MM/yy GGGG EEEEE
EEEEE, MM/d/yy GGGG
EEEEE, MM/dd/yy GGGG
MMMM yy GGGG EEEEE
EEEEE, MMMM d, yy GGGG
EEEEE, MMMM dd, yy GGGG
MMM yy GGGG EEEEE
EEEEE, MMM d, yy GGGG
EEEEE, MMM dd, yy GGGG
MMMMM yy GGGG EEEEE
EEEEE, MMMMM d, yy GGGG
EEEEE, MMMMM dd, yy GGGG
G EEEEE
d EEEEE G
dd EEEEE G
EEEEE, M/d G
EEEEE, M/dd G
EEEEE, MM/d G
EEEEE, MM/dd G
EEEEE, MMMM d G
EEEEE, MMMM dd G
EEEEE, MMM d G
EEEEE, MMM dd G
EEEEE, MMMMM d G
EEEEE, MMMMM dd G
y G EEEEE
y G' (day: 'd EEEEE)
y G' (day: 'dd EEEEE)
M/y G EEEEE
EEEEE, M/d/y G
EEEEE, M/dd/y G
MM/y G EEEEE
EEEEE, MM/d/y G
EEEEE, MM/dd/y G
MMMM y G EEEEE
EEEEE, MMMM d, y G
EEEEE, MMMM dd, y G
MMM y G EEEEE
EEEEE, MMM d, y G
EEEEE, MMM dd, y G
MMMMM y G EEEEE
EEEEE, MMMMM d, y G
EEEEE, MMMMM dd, y G
yy G EEEEE
yy G' (day: 'd EEEEE)
yy G' (day: 'dd EEEEE)
M/yy G EEEEE
EEEEE, M/d/yy G
EEEEE, M/dd/yy G
MM/yy G EEEEE
EEEEE, MM/d/yy G
EEEEE, MM/dd/yy G
MMMM yy G EEEEE
EEEEE, MMMM d, yy G
EEEEE, MMMM dd, yy G
MMM yy G EEEEE
EEEEE, MMM d, yy G
EEEEE, MMM dd, yy G
MMMMM yy G EEEEE
EEEEE, MMMMM d, yy G
EEEEE, MMMMM dd, yy G
GGGGG EEEEE
d EEEEE GGGGG
dd EEEEE GGGGG
EEEEE, M/d GGGGG
EEEEE, M/dd GGGGG
EEEEE, MM/d GGGGG
EEEEE, MM/dd GGGGG
EEEEE, MMMM d GGGGG
EEEEE, MMMM dd GGGGG
EEEEE, MMM d GGGGG
EEEEE, MMM dd GGGGG
EEEEE, MMMMM d GGGGG
EEEEE, MMMMM dd GGGGG
y GGGGG EEEEE
y GGGGG' (day: 'd EEEEE)
y GGGGG' (day: 'dd EEEEE)
M/y GGGGG EEEEE
EEEEE, M/d/y GGGGG
EEEEE, M/dd/y GGGGG
MM/y GGGGG EEEEE
EEEEE, MM/d/y GGGGG
EEEEE, MM/dd/y GGGGG
MMMM y GGGGG EEEEE
EEEEE, MMMM d, y GGGGG
EEEEE, MMMM dd, y GGGGG
MMM y GGGGG EEEEE
EEEEE, MMM d, y GGGGG
EEEEE, MMM dd, y GGGGG
MMMMM y GGGGG EEEEE
EEEEE, MMMMM d, y GGGGG
EEEEE, MMMMM dd, y GGGGG
yy GGGGG EEEEE
d EEEEE yy GGGGG
yy GGGGG' (day: 'dd EEEEE)
M/yy GGGGG EEEEE
EEEEE, M/d/yy GGGGG
EEEEE, M/dd/yy GGGGG
MM/yy GGGGG EEEEE
EEEEE, MM/d/yy GGGGG
EEEEE, MM/dd/yy GGGGG
MMMM yy GGGGG EEEEE
EEEEE, MMMM d, yy GGGGG
EEEEE, MMMM dd, yy GGGGG
MMM yy GGGGG EEEEE
EEEEE, MMM d, yy GGGGG
EEEEE, MMM dd, yy GGGGG
MMMMM yy GGGGG EEEEE
EEEEE, MMMMM d, yy GGGGG
EEEEE, MMMMM dd, yy GGGGG
s
m
mm:ss
K a
h a
HH
kk
K a' (second: 's)
h a' (second: 's)
HH' (second: 's)
s' (hour: 'kk)
K:mm a
h:mm a
HH:mm
kk:mm
K:mm:ss a
h:mm:ss a
HH:mm:ss
kk:mm:ss
KK a
hh a
KK a' (second: 's)
hh a' (second: 's)
s' (hour: 'HH)
KK:mm a
hh:mm a
KK:mm:ss a
hh:mm:ss a
K:mm:ss a zzzz
h:mm:ss a zzzz
HH:mm:ss zzzz
kk:mm:ss zzzz
K:mm:ss a z
h:mm:ss a z
HH:mm:ss z
kk:mm:ss z
EEEE, MMMM d, y' at 'K:mm:ss a zzzz
EEEE, MMMM d, y' at 'h:mm:ss a zzzz
EEEE, MMMM d, y' at 'HH:mm:ss zzzz
EEEE, MMMM d, y' at 'kk:mm:ss zzzz
EEEE, MMMM d, y' at 'K:mm:ss a z
EEEE, MMMM d, y' at 'h:mm:ss a z
EEEE, MMMM d, y' at 'HH:mm:ss z
EEEE, MMMM d, y' at 'kk:mm:ss z
EEEE, MMMM d, y' at 'K:mm:ss a
EEEE, MMMM d, y' at 'h:mm:ss a
EEEE, MMMM d, y' at 'HH:mm:ss
EEEE, MMMM d, y' at 'kk:mm:ss
EEEE, MMMM d, y' at 'K:mm a
EEEE, MMMM d, y' at 'h:mm a
EEEE, MMMM d, y' at 'HH:mm
EEEE, MMMM d, y' at 'kk:mm
MMMM d, y' at 'K:mm:ss a zzzz
MMMM d, y' at 'h:mm:ss a zzzz
MMMM d, y' at 'HH:mm:ss zzzz
MMMM d, y' at 'kk:mm:ss zzzz
MMMM d, y' at 'K:mm:ss a z
MMMM d, y' at 'h:mm:ss a z
MMMM d, y' at 'HH:mm:ss z
MMMM d, y' at 'kk:mm:ss z
MMMM d, y' at 'K:mm:ss a
MMMM d, y' at 'h:mm:ss a
MMMM d, y' at 'HH:mm:ss
MMMM d, y' at 'kk:mm:ss
MMMM d, y' at 'K:mm a
MMMM d, y' at 'h:mm a
MMMM d, y' at 'HH:mm
MMMM d, y' at 'kk:mm
MMM d, y, K:mm:ss a zzzz
MMM d, y, h:mm:ss a zzzz
MMM d, y, HH:mm:ss zzzz
MMM d, y, kk:mm:ss zzzz
MMM d, y, K:mm:ss a z
MMM d, y, h:mm:ss a z
MMM d, y, HH:mm:ss z
MMM d, y, kk:mm:ss z
MMM d, y, K:mm:ss a
MMM d, y, h:mm:ss a
MMM d, y, HH:mm:ss
MMM d, y, kk:mm:ss
MMM d, y, K:mm a
MMM d, y, h:mm a
MMM d, y, HH:mm
MMM d, y, kk:mm
M/d/yy, K:mm:ss a zzzz
M/d/yy, h:mm:ss a zzzz
M/d/yy, HH:mm:ss zzzz
M/d/yy, kk:mm:ss zzzz
M/d/yy, K:mm:ss a z
M/d/yy, h:mm:ss a z
M/d/yy, HH:mm:ss z
M/d/yy, kk:mm:ss z
M/d/yy, K:mm:ss a
M/d/yy, h:mm:ss a
M/d/yy, HH:mm:ss
M/d/yy, kk:mm:ss
M/d/yy, K:mm a
M/d/yy, h:mm a
M/d/yy, HH:mm
M/d/yy, kk:mm
, 
' at '
dd/MM
dd/M
d/MM
d MMMM
dd MMMM
d MMM
dd MMM
d MMMMM
dd MMMMM
dd/MM/y
dd/M/y
d/MM/y
d MMMM y
dd MMMM y
d MMM y
dd MMM y
d MMMMM y
dd MMMMM y
dd/MM/yy
dd/M/yy
d/MM/yy
d MMMM yy
dd MMMM yy
d MMM yy
dd MMM yy
d MMMMM yy
dd MMMMM yy
dd/MM/y GGGG
dd/MM GGGG
dd/M GGGG
d/MM GGGG
d MMMM GGGG
dd MMMM GGGG
d MMM GGGG
dd MMM GGGG
d MMMMM GGGG
dd MMMMM GGGG
d MMMM y GGGG
dd MMMM y GGGG
d MMM y GGGG
dd MMM y GGGG
d MMMMM y GGGG
dd MMMMM y GGGG
dd/MM/yy GGGG
d MMMM yy GGGG
dd MMMM yy GGGG
d MMM yy GGGG
dd MMM yy GGGG
d MMMMM yy GGGG
dd MMMMM yy GGGG
dd/MM/y G
dd/MM G
dd/M G
d/MM G
d MMMM G
dd MMMM G
d MMM G
dd MMM G
d MMMMM G
dd MMMMM G
d MMMM y G
dd MMMM y G
d MMM y G
dd MMM y G
d MMMMM y G
dd MMMMM y G
dd/MM/yy G
d MMMM yy G
dd MMMM yy G
d MMM yy G
dd MMM yy G
d MMMMM yy G
dd MMMMM yy G
dd/MM/y GGGGG
dd/MM GGGGG
dd/M GGGGG
d/MM GGGGG
d MMMM GGGGG
dd MMMM GGGGG
d MMM GGGGG
dd MMM GGGGG
d MMMMM GGGGG
dd MMMMM GGGGG
d MMMM y GGGGG
dd MMMM y GGGGG
d MMM y GGGGG
dd MMM y GGGGG
d MMMMM y GGGGG
dd MMMMM y GGGGG
dd/MM/yy GGGGG
d MMMM yy GGGGG
dd MMMM yy GGGGG
d MMM yy GGGGG
dd MMM yy GGGGG
d MMMMM yy GGGGG
dd MMMMM yy GGGGG
EEEE d
EEEE dd
EEEE dd/MM
EEEE d MMMM
EEEE dd MMMM
EEEE d MMM
EEEE dd MMM
EEEE d MMMMM
EEEE dd MMMMM
EEEE d y
EEEE dd y
EEEE, dd/MM/y
EEEE, d MMMM y
EEEE, dd MMMM y
EEEE, d MMM y
EEEE, dd MMM y
EEEE, d MMMMM y
EEEE, dd MMMMM y
EEEE d yy
EEEE dd yy
EEEE, dd/MM/yy
EEEE, d MMMM yy
EEEE, dd MMMM yy
EEEE, d MMM yy
EEEE, dd MMM yy
EEEE, d MMMMM yy
EEEE, dd MMMMM yy
EEEE d GGGG
EEEE dd GGGG
EEEE dd/MM GGGG
EEEE d MMMM GGGG
EEEE dd MMMM GGGG
EEEE d MMM GGGG
EEEE dd MMM GGGG
EEEE d MMMMM GGGG
EEEE dd MMMMM GGGG
y GGGG' (day: 'EEEE d)
y GGGG' (day: 'EEEE dd)
EEEE, d/M/y GGGG
EEEE, dd/M/y GGGG
EEEE, d/MM/y GGGG
EEEE, dd/MM/y GGGG
EEEE, d MMMM y GGGG
EEEE, dd MMMM y GGGG
EEEE, d MMM y GGGG
EEEE, dd MMM y GGGG
EEEE, d MMMMM y GGGG
EEEE, dd MMMMM y GGGG
EEEE d yy GGGG
yy GGGG' (day: 'EEEE dd)
EEEE, d/M/yy GGGG
EEEE, dd/M/yy GGGG
EEEE, d/MM/yy GGGG
EEEE, dd/MM/yy GGGG
EEEE, d MMMM yy GGGG
EEEE, dd MMMM yy GGGG
EEEE, d MMM yy GGGG
EEEE, dd MMM yy GGGG
EEEE, d MMMMM yy GGGG
EEEE, dd MMMMM yy GGGG
EEEE d G
EEEE dd G
EEEE dd/MM G
EEEE d MMMM G
EEEE dd MMMM G
EEEE d MMM G
EEEE dd MMM G
EEEE d MMMMM G
EEEE dd MMMMM G
y G' (day: 'EEEE d)
y G' (day: 'EEEE dd)
EEEE, d/M/y G
EEEE, dd/M/y G
EEEE, d/MM/y G
EEEE, dd/MM/y G
EEEE, d MMMM y G
EEEE, dd MMMM y G
EEEE, d MMM y G
EEEE, dd MMM y G
EEEE, d MMMMM y G
EEEE, dd MMMMM y G
yy G' (day: 'EEEE d)
yy G' (day: 'EEEE dd)
EEEE, d/M/yy G
EEEE, dd/M/yy G
EEEE, d/MM/yy G
EEEE, dd/MM/yy G
EEEE, d MMMM yy G
EEEE, dd MMMM yy G
EEEE, d MMM yy G
EEEE, dd MMM yy G
EEEE, d MMMMM yy G
EEEE, dd MMMMM yy G
EEEE d GGGGG
EEEE dd GGGGG
EEEE dd/MM GGGGG
EEEE d MMMM GGGGG
EEEE dd MMMM GGGGG
EEEE d MMM GGGGG
EEEE dd MMM GGGGG
EEEE d MMMMM GGGGG
EEEE dd MMMMM GGGGG
EEEE d y GGGGG
y GGGGG' (day: 'EEEE dd)
EEEE, d/M/y GGGGG
EEEE, dd/M/y GGGGG
EEEE, d/MM/y GGGGG
EEEE, dd/MM/y GGGGG
EEEE, d MMMM y GGGGG
EEEE, dd MMMM y GGGGG
EEEE, d MMM y GGGGG
EEEE, dd MMM y GGGGG
EEEE, d MMMMM y GGGGG
EEEE, dd MMMMM y GGGGG
EEEE d yy GGGGG
EEEE dd yy GGGGG
EEEE, d/M/yy GGGGG
EEEE, dd/M/yy GGGGG
EEEE, d/MM/yy GGGGG
EEEE, dd/MM/yy GGGGG
EEEE, d MMMM yy GGGGG
EEEE, dd MMMM yy GGGGG
EEEE, d MMM yy GGGGG
EEEE, dd MMM yy GGGGG
EEEE, d MMMMM yy GGGGG
EEEE, dd MMMMM yy GGGGG
EEE d
EEE dd
EEE dd/MM
EEE d MMMM
EEE dd MMMM
EEE d MMM
EEE dd MMM
EEE d MMMMM
EEE dd MMMMM
EEE d y
EEE dd y
EEE, dd/MM/y
EEE, d MMMM y
EEE, dd MMMM y
EEE, d MMM y
EEE, dd MMM y
EEE, d MMMMM y
EEE, dd MMMMM y
EEE d yy
EEE dd yy
EEE, dd/MM/yy
EEE, d MMMM yy
EEE, dd MMMM yy
EEE, d MMM yy
EEE, dd MMM yy
EEE, d MMMMM yy
EEE, dd MMMMM yy
EEE d GGGG
EEE dd GGGG
EEE dd/MM GGGG
EEE d MMMM GGGG
EEE dd MMMM GGGG
EEE d MMM GGGG
EEE dd MMM GGGG
EEE d MMMMM GGGG
EEE dd MMMMM GGGG
EEE d y GGGG
y GGGG' (day: 'EEE dd)
EEE, d/M/y GGGG
EEE, dd/M/y GGGG
EEE, d/MM/y GGGG
EEE, dd/MM/y GGGG
EEE, d MMMM y GGGG
EEE, dd MMMM y GGGG
EEE, d MMM y GGGG
EEE, dd MMM y GGGG
EEE, d MMMMM y GGGG
EEE, dd MMMMM y GGGG
EEE d yy GGGG
EEE dd yy GGGG
EEE, d/M/yy GGGG
EEE, dd/M/yy GGGG
EEE, d/MM/yy GGGG
EEE, dd/MM/yy GGGG
EEE, d MMMM yy GGGG
EEE, dd MMMM yy GGGG
EEE, d MMM yy GGGG
EEE, dd MMM yy GGGG
EEE, d MMMMM yy GGGG
EEE, dd MMMMM yy GGGG
EEE d G
EEE dd G
EEE dd/MM G
EEE d MMMM G
EEE dd MMMM G
EEE d MMM G
EEE dd MMM G
EEE d MMMMM G
EEE dd MMMMM G
y G' (day: 'EEE d)
y G' (day: 'EEE dd)
EEE, d/M/y G
EEE, dd/M/y G
EEE, d/MM/y G
EEE, dd/MM/y G
EEE, d MMMM y G
EEE, dd MMMM y G
EEE, d MMM y G
EEE, dd MMM y G
EEE, d MMMMM y G
EEE, dd MMMMM y G
EEE d yy G
yy G' (day: 'EEE dd)
EEE, d/M/yy G
EEE, dd/M/yy G
EEE, d/MM/yy G
EEE, dd/MM/yy G
EEE, d MMMM yy G
EEE, dd MMMM yy G
EEE, d MMM yy G
EEE, dd MMM yy G
EEE, d MMMMM yy G
EEE, dd MMMMM yy G
EEE d GGGGG
EEE dd GGGGG
EEE dd/MM GGGGG
EEE d MMMM GGGGG
EEE dd MMMM GGGGG
EEE d MMM GGGGG
EEE dd MMM GGGGG
EEE d MMMMM GGGGG
EEE dd MMMMM GGGGG
EEE d y GGGGG
EEE dd y GGGGG
EEE, d/M/y GGGGG
EEE, dd/M/y GGGGG
EEE, d/MM/y GGGGG
EEE, dd/MM/y GGGGG
EEE, d MMMM y GGGGG
EEE, dd MMMM y GGGGG
EEE, d MMM y GGGGG
EEE, dd MMM y GGGGG
EEE, d MMMMM y GGGGG
EEE, dd MMMMM y GGGGG
EEE d yy GGGGG
EEE dd yy GGGGG
EEE, d/M/yy GGGGG
EEE, dd/M/yy GGGGG
EEE, d/MM/yy GGGGG
EEE, dd/MM/yy GGGGG
EEE, d MMMM yy GGGGG
EEE, dd MMMM yy GGGGG
EEE, d MMM yy GGGGG
EEE, dd MMM yy GGGGG
EEE, d MMMMM yy GGGGG
EEE, dd MMMMM yy GGGGG
EEEEE d
EEEEE dd
EEEEE dd/MM
EEEEE d MMMM
EEEEE dd MMMM
EEEEE d MMM
EEEEE dd MMM
EEEEE d MMMMM
EEEEE dd MMMMM
EEEEE d y
EEEEE dd y
EEEEE, dd/MM/y
EEEEE, d MMMM y
EEEEE, dd MMMM y
EEEEE, d MMM y
EEEEE, dd MMM y
EEEEE, d MMMMM y
EEEEE, dd MMMMM y
EEEEE d yy
EEEEE dd yy
EEEEE, dd/MM/yy
EEEEE, d MMMM yy
EEEEE, dd MMMM yy
EEEEE, d MMM yy
EEEEE, dd MMM yy
EEEEE, d MMMMM yy
EEEEE, dd MMMMM yy
EEEEE d GGGG
EEEEE dd GGGG
EEEEE dd/MM GGGG
EEEEE d MMMM GGGG
EEEEE dd MMMM GGGG
EEEEE d MMM GGGG
EEEEE dd MMM GGGG
EEEEE d MMMMM GGGG
EEEEE dd MMMMM GGGG
y GGGG' (day: 'EEEEE d)
y GGGG' (day: 'EEEEE dd)
EEEEE, d/M/y GGGG
EEEEE, dd/M/y GGGG
EEEEE, d/MM/y GGGG
EEEEE, dd/MM/y GGGG
EEEEE, d MMMM y GGGG
EEEEE, dd MMMM y GGGG
EEEEE, d MMM y GGGG
EEEEE, dd MMM y GGGG
EEEEE, d MMMMM y GGGG
EEEEE, dd MMMMM y GGGG
yy GGGG' (day: 'EEEEE d)
yy GGGG' (day: 'EEEEE dd)
EEEEE, d/M/yy GGGG
EEEEE, dd/M/yy GGGG
EEEEE, d/MM/yy GGGG
EEEEE, dd/MM/yy GGGG
EEEEE, d MMMM yy GGGG
EEEEE, dd MMMM yy GGGG
EEEEE, d MMM yy GGGG
EEEEE, dd MMM yy GGGG
EEEEE, d MMMMM yy GGGG
EEEEE, dd MMMMM yy GGGG
EEEEE d G
EEEEE dd G
EEEEE dd/MM G
EEEEE d MMMM G
EEEEE dd MMMM G
EEEEE d MMM G
EEEEE dd MMM G
EEEEE d MMMMM G
EEEEE dd MMMMM G
y G' (day: 'EEEEE d)
y G' (day: 'EEEEE dd)
EEEEE, d/M/y G
EEEEE, dd/M/y G
EEEEE, d/MM/y G
EEEEE, dd/MM/y G
EEEEE, d MMMM y G
EEEEE, dd MMMM y G
EEEEE, d MMM y G
EEEEE, dd MMM y G
EEEEE, d MMMMM y G
EEEEE, dd MMMMM y G
yy G' (day: 'EEEEE d)
yy G' (day: 'EEEEE dd)
EEEEE, d/M/yy G
EEEEE, dd/M/yy G
EEEEE, d/MM/yy G
EEEEE, dd/MM/yy G
EEEEE, d MMMM yy G
EEEEE, dd MMMM yy G
EEEEE, d MMM yy G
EEEEE, dd MMM yy G
EEEEE, d MMMMM yy G
EEEEE, dd MMMMM yy G
EEEEE d GGGGG
EEEEE dd GGGGG
EEEEE dd/MM GGGGG
EEEEE d MMMM GGGGG
EEEEE dd MMMM GGGGG
EEEEE d MMM GGGGG
EEEEE dd MMM GGGGG
EEEEE d MMMMM GGGGG
EEEEE dd MMMMM GGGGG
y GGGGG' (day: 'EEEEE d)
y GGGGG' (day: 'EEEEE dd)
EEEEE, d/M/y GGGGG
EEEEE, dd/M/y GGGGG
EEEEE, d/MM/y GGGGG
EEEEE, dd/MM/y GGGGG
EEEEE, d MMMM y GGGGG
EEEEE, dd MMMM y GGGGG
EEEEE, d MMM y GGGGG
EEEEE, dd MMM y GGGGG
EEEEE, d MMMMM y GGGGG
EEEEE, dd MMMMM y GGGGG
EEEEE d yy GGGGG
yy GGGGG' (day: 'EEEEE dd)
EEEEE, d/M/yy GGGGG
EEEEE, dd/M/yy GGGGG
EEEEE, d/MM/yy GGGGG
EEEEE, dd/MM/yy GGGGG
EEEEE, d MMMM yy GGGGG
EEEEE, dd MMMM yy GGGGG
EEEEE, d MMM yy GGGGG
EEEEE, dd MMM yy GGGGG
EEEEE, d MMMMM yy GGGGG
EEEEE, dd MMMMM yy GGGGG
k:mm
k:mm:ss
H:mm
H:mm:ss
KK:mm:ss a zzzz
hh:mm:ss a zzzz
KK:mm:ss a z
hh:mm:ss a z
EEEE, d MMMM y' at 'KK:mm:ss a zzzz
EEEE, d MMMM y' at 'hh:mm:ss a zzzz
EEEE, d MMMM y' at 'HH:mm:ss zzzz
EEEE, d MMMM y' at 'kk:mm:ss zzzz
EEEE, d MMMM y' at 'KK:mm:ss a z
EEEE, d MMMM y' at 'hh:mm:ss a z
EEEE, d MMMM y' at 'HH:mm:ss z
EEEE, d MMMM y' at 'kk:mm:ss z
EEEE, d MMMM y' at 'KK:mm:ss a
EEEE, d MMMM y' at 'hh:mm:ss a
EEEE, d MMMM y' at 'HH:mm:ss
EEEE, d MMMM y' at 'kk:mm:ss
EEEE, d MMMM y' at 'KK:mm a
EEEE, d MMMM y' at 'hh:mm a
EEEE, d MMMM y' at 'HH:mm
EEEE, d MMMM y' at 'kk:mm
d MMMM y' at 'KK:mm:ss a zzzz
d MMMM y' at 'hh:mm:ss a zzzz
d MMMM y' at 'HH:mm:ss zzzz
d MMMM y' at 'kk:mm:ss zzzz
d MMMM y' at 'KK:mm:ss a z
d MMMM y' at 'hh:mm:ss a z
d MMMM y' at 'HH:mm:ss z
d MMMM y' at 'kk:mm:ss z
d MMMM y' at 'KK:mm:ss a
d MMMM y' at 'hh:mm:ss a
d MMMM y' at 'HH:mm:ss
d MMMM y' at 'kk:mm:ss
d MMMM y' at 'KK:mm a
d MMMM y' at 'hh:mm a
d MMMM y' at 'HH:mm
d MMMM y' at 'kk:mm
d MMM y, KK:mm:ss a zzzz
d MMM y, hh:mm:ss a zzzz
d MMM y, HH:mm:ss zzzz
d MMM y, kk:mm:ss zzzz
d MMM y, KK:mm:ss a z
d MMM y, hh:mm:ss a z
d MMM y, HH:mm:ss z
d MMM y, kk:mm:ss z
d MMM y, KK:mm:ss a
d MMM y, hh:mm:ss a
d MMM y, HH:mm:ss
d MMM y, kk:mm:ss
d MMM y, KK:mm a
d MMM y, hh:mm a
d MMM y, HH:mm
d MMM y, kk:mm
dd/MM/y, KK:mm:ss a zzzz
dd/MM/y, hh:mm:ss a zzzz
dd/MM/y, HH:mm:ss zzzz
dd/MM/y, kk:mm:ss zzzz
dd/MM/y, KK:mm:ss a z
dd/MM/y, hh:mm:ss a z
dd/MM/y, HH:mm:ss z
dd/MM/y, kk:mm:ss z
dd/MM/y, KK:mm:ss a
dd/MM/y, hh:mm:ss a
dd/MM/y, HH:mm:ss
dd/MM/y, kk:mm:ss
dd/MM/y, KK:mm a
dd/MM/y, hh:mm a
dd/MM/y, HH:mm
dd/MM/y, kk:mm";

/// Locale data for one supported locale.
pub(super) struct LocaleData {
    /// The canonical tag `resolvedOptions().locale` reports.
    pub(super) tag: &'static str,
    /// Date patterns indexed by `date_signature`.
    pub(super) dates: &'static [u16; 864],
    /// Time patterns indexed by `time_signature`.
    pub(super) times: &'static [u16; 108],
    /// Glue joining a date pattern to a time pattern, indexed by
    /// `month_width * 2 + weekday_present`.
    pub(super) glue: &'static [u16; 12],
    /// Patterns for the style shorthands, indexed by
    /// `(date_style * 5 + time_style) * 4 + hour_cycle`.
    pub(super) styles: &'static [u16; 100],
    /// Month names in long, short, and narrow width, January first.
    pub(super) months: [[&'static str; 12]; 3],
    /// Weekday names in long, short, and narrow width, Sunday first.
    pub(super) weekdays: [[&'static str; 7]; 3],
    /// Era names in long, short, and narrow width, BC then AD.
    pub(super) eras: [[&'static str; 2]; 3],
    /// The AM and PM day period names.
    pub(super) day_periods: [&'static str; 2],
    /// UTC's short and long names, which a style pattern's zone token renders
    /// when the request names UTC.
    pub(super) zone_names: [&'static str; 2],
    /// The hour cycle a request that names none resolves to.
    pub(super) hour_cycle: &'static str,
}

static EN_US_DATES: [u16; 864] = [
    NONE, 212, 413, 614, 53, 266, 467, 668, 106, 315, 516, 717, 159, 364, 565, 766, 17, 230, 431,
    632, 71, 279, 480, 681, 124, 328, 529, 730, 177, 377, 578, 779, 35, 248, 449, 650, 88, 297,
    498, 699, 141, 346, 547, 748, 194, 395, 596, 797, 2, 215, 416, 617, 56, 56, 416, 56, 109, 109,
    109, 109, 162, 215, 416, 162, 20, 233, 434, 635, 74, 282, 483, 684, 127, 331, 532, 733, 180,
    380, 581, 782, 38, 251, 452, 653, 91, 300, 501, 702, 144, 349, 550, 751, 197, 398, 599, 800, 5,
    218, 419, 620, 59, 59, 467, 59, 112, 112, 516, 112, 165, 218, 419, 165, 23, 236, 437, 638, 76,
    285, 486, 687, 129, 334, 535, 736, 182, 383, 584, 785, 41, 254, 455, 656, 94, 303, 504, 705,
    147, 352, 553, 754, 200, 401, 602, 803, 8, 221, 422, 623, 62, 62, 467, 62, 115, 115, 516, 115,
    168, 221, 422, 168, 26, 239, 440, 641, 79, 288, 489, 690, 132, 337, 538, 739, 185, 386, 587,
    788, 44, 257, 458, 659, 97, 306, 507, 708, 150, 355, 556, 757, 203, 404, 605, 806, 11, 224,
    425, 626, 65, 65, 425, 65, 118, 118, 118, 118, 171, 224, 425, 171, 29, 242, 443, 644, 82, 291,
    492, 693, 135, 340, 541, 742, 188, 389, 590, 791, 47, 260, 461, 662, 100, 309, 510, 711, 153,
    358, 559, 760, 206, 407, 608, 809, 14, 227, 428, 629, 68, 266, 467, 68, 121, 315, 516, 121,
    174, 364, 565, 174, 32, 245, 446, 647, 85, 294, 495, 696, 138, 343, 544, 745, 191, 392, 593,
    794, 50, 263, 464, 665, 103, 312, 513, 714, 156, 361, 562, 763, 209, 410, 611, 812, 0, 213,
    414, 615, 54, 267, 468, 669, 107, 316, 517, 718, 160, 365, 566, 767, 18, 231, 432, 633, 72,
    280, 481, 682, 125, 329, 530, 731, 178, 378, 579, 780, 36, 249, 450, 651, 89, 298, 499, 700,
    142, 347, 548, 749, 195, 396, 597, 798, 3, 216, 417, 618, 57, 269, 470, 671, 110, 318, 519,
    720, 163, 367, 568, 769, 21, 234, 435, 636, 53, 283, 484, 685, 106, 332, 533, 734, 159, 381,
    582, 783, 39, 252, 453, 654, 92, 301, 502, 703, 145, 350, 551, 752, 198, 399, 600, 801, 6, 219,
    420, 621, 60, 271, 472, 673, 113, 320, 521, 722, 166, 369, 570, 771, 24, 237, 438, 639, 77,
    286, 487, 688, 130, 335, 536, 737, 183, 384, 585, 786, 42, 255, 456, 657, 95, 304, 505, 706,
    148, 353, 554, 755, 201, 402, 603, 804, 9, 222, 423, 624, 63, 273, 474, 675, 116, 322, 523,
    724, 169, 371, 572, 773, 27, 240, 441, 642, 80, 289, 490, 691, 133, 338, 539, 740, 186, 387,
    588, 789, 45, 258, 459, 660, 98, 307, 508, 709, 151, 356, 557, 758, 204, 405, 606, 807, 12,
    225, 426, 627, 66, 275, 476, 677, 119, 324, 525, 726, 172, 373, 574, 775, 30, 243, 444, 645,
    83, 292, 493, 694, 136, 341, 542, 743, 189, 390, 591, 792, 48, 261, 462, 663, 101, 310, 511,
    712, 154, 359, 560, 761, 207, 408, 609, 810, 15, 228, 429, 630, 69, 277, 478, 679, 122, 326,
    527, 728, 175, 375, 576, 777, 33, 246, 447, 648, 86, 295, 496, 697, 139, 344, 545, 746, 192,
    393, 594, 795, 51, 264, 465, 666, 104, 313, 514, 715, 157, 362, 563, 764, 210, 411, 612, 813,
    1, 214, 415, 616, 55, 268, 469, 670, 108, 317, 518, 719, 161, 366, 567, 768, 19, 232, 433, 634,
    73, 281, 482, 683, 126, 330, 531, 732, 179, 379, 580, 781, 37, 250, 451, 652, 90, 299, 500,
    701, 143, 348, 549, 750, 196, 397, 598, 799, 4, 217, 418, 619, 58, 270, 471, 672, 111, 319,
    520, 721, 164, 368, 569, 770, 22, 235, 436, 637, 75, 284, 485, 686, 128, 333, 534, 735, 181,
    382, 583, 784, 40, 253, 454, 655, 93, 302, 503, 704, 146, 351, 552, 753, 199, 400, 601, 802, 7,
    220, 421, 622, 61, 272, 473, 674, 114, 321, 522, 723, 167, 370, 571, 772, 25, 238, 439, 640,
    78, 287, 488, 689, 131, 336, 537, 738, 184, 385, 586, 787, 43, 256, 457, 658, 96, 305, 506,
    707, 149, 354, 555, 756, 202, 403, 604, 805, 10, 223, 424, 625, 64, 274, 475, 676, 117, 323,
    524, 725, 170, 372, 573, 774, 28, 241, 442, 643, 81, 290, 491, 692, 134, 339, 540, 741, 187,
    388, 589, 790, 46, 259, 460, 661, 99, 308, 509, 710, 152, 357, 558, 759, 205, 406, 607, 808,
    13, 226, 427, 628, 67, 276, 477, 678, 120, 325, 526, 727, 173, 374, 575, 776, 31, 244, 445,
    646, 84, 293, 494, 695, 137, 342, 543, 744, 190, 391, 592, 793, 49, 262, 463, 664, 102, 311,
    512, 713, 155, 360, 561, 762, 208, 409, 610, 811, 16, 229, 430, 631, 70, 278, 479, 680, 123,
    327, 528, 729, 176, 376, 577, 778, 34, 247, 448, 649, 87, 296, 497, 698, 140, 345, 546, 747,
    193, 394, 595, 796, 52, 265, 466, 667, 105, 314, 515, 716, 158, 363, 564, 765, 211, 412, 613,
    814,
];

static EN_US_TIMES: [u16; 108] = [
    NONE, 818, 834, 816, 826, 839, 816, 826, 839, 815, 822, 836, 817, 830, 841, 817, 830, 841, 815,
    822, 836, 817, 830, 841, 817, 830, 841, NONE, 819, 835, NONE, 827, 840, NONE, 827, 840, NONE,
    823, 837, NONE, 831, 842, NONE, 831, 842, NONE, 823, 837, NONE, 831, 842, NONE, 831, 842, NONE,
    820, 820, NONE, 828, 828, NONE, 828, 828, NONE, 824, 838, NONE, 832, 832, NONE, 832, 832, NONE,
    824, 824, NONE, 832, 832, NONE, 832, 832, NONE, 821, 821, NONE, 829, 829, NONE, 829, 829, NONE,
    825, 825, NONE, 833, 833, NONE, 833, 833, NONE, 825, 825, NONE, 833, 833, NONE, 833, 833,
];

static EN_US_GLUE: [u16; 12] = [915, 915, 915, 915, 915, 915, 916, 916, 915, 915, 915, 915];

static EN_US_STYLES: [u16; 100] = [
    NONE, NONE, NONE, NONE, 843, 844, 845, 846, 847, 848, 849, 850, 830, 831, 832, 833, 826, 827,
    828, 829, 240, NONE, NONE, NONE, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862,
    863, 864, 865, 866, 27, NONE, NONE, NONE, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876,
    877, 878, 879, 880, 881, 882, 30, NONE, NONE, NONE, 883, 884, 885, 886, 887, 888, 889, 890,
    891, 892, 893, 894, 895, 896, 897, 898, 39, NONE, NONE, NONE, 899, 900, 901, 902, 903, 904,
    905, 906, 907, 908, 909, 910, 911, 912, 913, 914,
];

static EN_GB_DATES: [u16; 864] = [
    NONE, 212, 413, 614, 944, 266, 467, 668, 967, 315, 516, 717, 990, 364, 565, 766, 17, 230, 431,
    632, 71, 279, 480, 681, 124, 328, 529, 730, 177, 377, 578, 779, 35, 248, 449, 650, 88, 297,
    498, 699, 141, 346, 547, 748, 194, 395, 596, 797, 2, 215, 416, 617, 56, 56, 416, 56, 109, 109,
    109, 109, 162, 215, 416, 162, 23, 236, 437, 638, 74, 282, 483, 684, 127, 331, 532, 733, 180,
    380, 581, 782, 41, 254, 455, 656, 91, 300, 501, 702, 144, 349, 550, 751, 197, 398, 599, 800, 5,
    218, 419, 620, 59, 59, 467, 59, 112, 112, 516, 112, 165, 218, 419, 165, 23, 236, 437, 638, 76,
    285, 486, 687, 129, 334, 535, 736, 182, 383, 584, 785, 41, 254, 455, 656, 94, 303, 504, 705,
    147, 352, 553, 754, 200, 401, 602, 803, 8, 221, 422, 623, 62, 62, 467, 62, 115, 115, 516, 115,
    168, 221, 422, 168, 26, 239, 440, 641, 79, 288, 489, 690, 132, 337, 538, 739, 185, 386, 587,
    788, 44, 257, 458, 659, 97, 306, 507, 708, 150, 355, 556, 757, 203, 404, 605, 806, 11, 224,
    425, 626, 65, 65, 425, 65, 118, 118, 118, 118, 171, 224, 425, 171, 29, 242, 443, 644, 82, 291,
    492, 693, 135, 340, 541, 742, 188, 389, 590, 791, 47, 260, 461, 662, 100, 309, 510, 711, 153,
    358, 559, 760, 206, 407, 608, 809, 14, 227, 428, 629, 68, 266, 467, 68, 121, 315, 516, 121,
    174, 364, 565, 174, 32, 245, 446, 647, 85, 294, 495, 696, 138, 343, 544, 745, 191, 392, 593,
    794, 50, 263, 464, 665, 103, 312, 513, 714, 156, 361, 562, 763, 209, 410, 611, 812, 0, 1013,
    1139, 1265, 54, 1040, 1166, 1292, 107, 1073, 1199, 1325, 160, 1106, 1232, 1358, 18, 1022, 1148,
    1274, 72, 1049, 1175, 1301, 125, 1082, 1208, 1334, 178, 1115, 1241, 1367, 36, 1031, 1157, 1283,
    89, 1061, 1187, 1313, 142, 1094, 1220, 1346, 195, 1127, 1253, 1379, 917, 1015, 1141, 1267, 945,
    1042, 1168, 1294, 968, 1075, 1201, 1327, 991, 1108, 1234, 1360, 926, 1024, 1150, 1276, 944,
    1051, 1177, 1303, 967, 1084, 1210, 1336, 990, 1117, 1243, 1369, 935, 1033, 1159, 1285, 960,
    1063, 1189, 1315, 983, 1096, 1222, 1348, 1006, 1129, 1255, 1381, 919, 1015, 1141, 1267, 947,
    1042, 1168, 1294, 970, 1075, 1201, 1327, 993, 1108, 1234, 1360, 928, 1024, 1150, 1276, 944,
    1053, 1179, 1305, 967, 1086, 1212, 1338, 990, 1119, 1245, 1371, 937, 1033, 1159, 1285, 960,
    1065, 1191, 1317, 983, 1098, 1224, 1350, 1006, 1131, 1257, 1383, 920, 1016, 1142, 1268, 948,
    1043, 1169, 1295, 971, 1076, 1202, 1328, 994, 1109, 1235, 1361, 929, 1025, 1151, 1277, 954,
    1055, 1181, 1307, 977, 1088, 1214, 1340, 1000, 1121, 1247, 1373, 938, 1034, 1160, 1286, 961,
    1067, 1193, 1319, 984, 1100, 1226, 1352, 1007, 1133, 1259, 1385, 922, 1018, 1144, 1270, 950,
    1045, 1171, 1297, 973, 1078, 1204, 1330, 996, 1111, 1237, 1363, 931, 1027, 1153, 1279, 956,
    1057, 1183, 1309, 979, 1090, 1216, 1342, 1002, 1123, 1249, 1375, 940, 1036, 1162, 1288, 963,
    1069, 1195, 1321, 986, 1102, 1228, 1354, 1009, 1135, 1261, 1387, 924, 1020, 1146, 1272, 952,
    1047, 1173, 1299, 975, 1080, 1206, 1332, 998, 1113, 1239, 1365, 933, 1029, 1155, 1281, 958,
    1059, 1185, 1311, 981, 1092, 1218, 1344, 1004, 1125, 1251, 1377, 942, 1038, 1164, 1290, 965,
    1071, 1197, 1323, 988, 1104, 1230, 1356, 1011, 1137, 1263, 1389, 1, 1014, 1140, 1266, 55, 1041,
    1167, 1293, 108, 1074, 1200, 1326, 161, 1107, 1233, 1359, 19, 1023, 1149, 1275, 73, 1050, 1176,
    1302, 126, 1083, 1209, 1335, 179, 1116, 1242, 1368, 37, 1032, 1158, 1284, 90, 1062, 1188, 1314,
    143, 1095, 1221, 1347, 196, 1128, 1254, 1380, 918, 1015, 1141, 1267, 946, 1042, 1168, 1294,
    969, 1075, 1201, 1327, 992, 1108, 1234, 1360, 927, 1024, 1150, 1276, 944, 1052, 1178, 1304,
    967, 1085, 1211, 1337, 990, 1118, 1244, 1370, 936, 1033, 1159, 1285, 960, 1064, 1190, 1316,
    983, 1097, 1223, 1349, 1006, 1130, 1256, 1382, 917, 1015, 1141, 1267, 945, 1042, 1168, 1294,
    968, 1075, 1201, 1327, 991, 1108, 1234, 1360, 926, 1024, 1150, 1276, 944, 1054, 1180, 1306,
    967, 1087, 1213, 1339, 990, 1120, 1246, 1372, 935, 1033, 1159, 1285, 960, 1066, 1192, 1318,
    983, 1099, 1225, 1351, 1006, 1132, 1258, 1384, 921, 1017, 1143, 1269, 949, 1044, 1170, 1296,
    972, 1077, 1203, 1329, 995, 1110, 1236, 1362, 930, 1026, 1152, 1278, 955, 1056, 1182, 1308,
    978, 1089, 1215, 1341, 1001, 1122, 1248, 1374, 939, 1035, 1161, 1287, 962, 1068, 1194, 1320,
    985, 1101, 1227, 1353, 1008, 1134, 1260, 1386, 923, 1019, 1145, 1271, 951, 1046, 1172, 1298,
    974, 1079, 1205, 1331, 997, 1112, 1238, 1364, 932, 1028, 1154, 1280, 957, 1058, 1184, 1310,
    980, 1091, 1217, 1343, 1003, 1124, 1250, 1376, 941, 1037, 1163, 1289, 964, 1070, 1196, 1322,
    987, 1103, 1229, 1355, 1010, 1136, 1262, 1388, 925, 1021, 1147, 1273, 953, 1048, 1174, 1300,
    976, 1081, 1207, 1333, 999, 1114, 1240, 1366, 934, 1030, 1156, 1282, 959, 1060, 1186, 1312,
    982, 1093, 1219, 1345, 1005, 1126, 1252, 1378, 943, 1039, 1165, 1291, 966, 1072, 1198, 1324,
    989, 1105, 1231, 1357, 1012, 1138, 1264, 1390,
];

static EN_GB_TIMES: [u16; 108] = [
    NONE, 818, 834, 816, 826, 839, 816, 826, 839, 815, 822, 836, 817, 830, 841, 817, 830, 841, 815,
    822, 836, 817, 830, 841, 817, 830, 841, NONE, 819, 835, NONE, 827, 840, NONE, 827, 840, NONE,
    823, 837, NONE, 831, 842, NONE, 831, 842, NONE, 823, 837, NONE, 831, 842, NONE, 831, 842, NONE,
    820, 820, NONE, 828, 828, NONE, 1393, 828, NONE, 824, 838, NONE, 832, 832, NONE, 832, 832,
    NONE, 824, 824, NONE, 832, 832, NONE, 1394, 832, NONE, 821, 821, NONE, 1391, 829, NONE, 1391,
    829, NONE, 825, 825, NONE, 833, 833, NONE, 1392, 833, NONE, 825, 825, NONE, 1392, 833, NONE,
    1392, 833,
];

static EN_GB_GLUE: [u16; 12] = [915, 915, 915, 915, 915, 915, 916, 916, 915, 915, 915, 915];

static EN_GB_STYLES: [u16; 100] = [
    NONE, NONE, NONE, NONE, 1395, 1396, 845, 846, 1397, 1398, 849, 850, 841, 842, 832, 833, 839,
    840, 828, 829, 1025, NONE, NONE, NONE, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407,
    1408, 1409, 1410, 1411, 1412, 1413, 1414, 929, NONE, NONE, NONE, 1415, 1416, 1417, 1418, 1419,
    1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 931, NONE, NONE, NONE, 1431,
    1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 926,
    NONE, NONE, NONE, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459,
    1460, 1461, 1462,
];

/// Every locale this build formats. A request outside the set negotiates to
/// the first entry, which `resolvedOptions().locale` then reports.
pub(super) static LOCALES: &[LocaleData] = &[
    LocaleData {
        tag: "en-US",
        dates: &EN_US_DATES,
        times: &EN_US_TIMES,
        glue: &EN_US_GLUE,
        styles: &EN_US_STYLES,
        months: [
            [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
            ],
            [
                "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
            ],
            ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"],
        ],
        weekdays: [
            [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
            ],
            ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            ["S", "M", "T", "W", "T", "F", "S"],
        ],
        eras: [["Before Christ", "Anno Domini"], ["BC", "AD"], ["B", "A"]],
        day_periods: ["AM", "PM"],
        zone_names: ["UTC", "Coordinated Universal Time"],
        hour_cycle: "h12",
    },
    LocaleData {
        tag: "en-GB",
        dates: &EN_GB_DATES,
        times: &EN_GB_TIMES,
        glue: &EN_GB_GLUE,
        styles: &EN_GB_STYLES,
        months: [
            [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
            ],
            [
                "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec",
            ],
            ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"],
        ],
        weekdays: [
            [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
            ],
            ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            ["S", "M", "T", "W", "T", "F", "S"],
        ],
        eras: [["Before Christ", "Anno Domini"], ["BC", "AD"], ["B", "A"]],
        day_periods: ["am", "pm"],
        zone_names: ["UTC", "Coordinated Universal Time"],
        hour_cycle: "h23",
    },
];
