/*
 * Emit silksurf-js/tests/fixtures/intl_datetime_vectors.js, the conformance
 * fixture Intl.DateTimeFormat is checked against.
 *
 * Each vector names a locale, an option bag, an instant, and the text the
 * reference ECMA-402 implementation renders for it. The date and time
 * signatures are enumerated in full, so every width combination the resolved
 * pattern tables carry is asserted; the combined cases sample the cross
 * product, which is too large to enumerate and adds only the glue.
 */
const WEEKDAY = [null,'long','short','narrow'], ERA = [null,'long','short','narrow'];
const YEAR = [null,'numeric','2-digit'], MONTH = [null,'numeric','2-digit','long','short','narrow'];
const DAY = [null,'numeric','2-digit'], NUM2 = [null,'numeric','2-digit'];
const CYCLES = ['h11','h12','h23','h24'];
/*
 * Every month and every weekday appear, so each name in the generated table is
 * compared against the reference implementation at least once. The last two
 * instants pin midnight, noon, the end of a year, and a leap day.
 */
const INSTANTS = [
  Date.UTC(2026, 0, 5, 4, 5, 6, 70),    Date.UTC(2026, 1, 10, 9, 30, 0),
  Date.UTC(2026, 2, 18, 14, 5, 9, 123), Date.UTC(2026, 3, 23, 18, 45, 30),
  Date.UTC(2026, 4, 1, 23, 15, 1),      Date.UTC(2026, 5, 13, 6, 7, 8),
  Date.UTC(2026, 6, 28, 11, 59, 59),    Date.UTC(2026, 7, 20, 14, 5, 9, 123),
  Date.UTC(2026, 8, 2, 0, 0, 0),        Date.UTC(2026, 9, 16, 12, 0, 0, 500),
  Date.UTC(2026, 10, 25, 21, 21, 21),   Date.UTC(2026, 11, 31, 23, 59, 59, 999),
  Date.UTC(1999, 11, 31, 23, 59, 59),   Date.UTC(2024, 1, 29, 12, 0, 0),
];
const locales = (process.argv[2] || 'en-US,en-GB').split(',');
const vectors = [];
let n = 0;
// [weekday, era, year, month, day, hour, minute, second, hourCycle,
//  dateStyle, timeStyle], each an ordinal into the tables above with 0 absent.
const push = (locale, code) => {
  const o = { timeZone: 'UTC' };
  if (code[0]) o.weekday = WEEKDAY[code[0]]; if (code[1]) o.era = ERA[code[1]];
  if (code[2]) o.year = YEAR[code[2]]; if (code[3]) o.month = MONTH[code[3]];
  if (code[4]) o.day = DAY[code[4]]; if (code[5]) o.hour = NUM2[code[5]];
  if (code[6]) o.minute = NUM2[code[6]]; if (code[7]) o.second = NUM2[code[7]];
  if (code[8]) o.hourCycle = CYCLES[code[8] - 1];
  if (code[9]) o.dateStyle = STYLES[code[9]]; if (code[10]) o.timeStyle = STYLES[code[10]];
  const t = INSTANTS[n % INSTANTS.length];
  n++;
  let text;
  try { text = new Intl.DateTimeFormat(locale, o).format(t); } catch { return; }
  while (code.length && code[code.length - 1] === 0) code.pop();
  vectors.push([locales.indexOf(locale), code, t, text]);
};
const STYLES = [null, 'full', 'long', 'medium', 'short'];
for (const locale of locales) {
  for (let w = 0; w < 4; w++) for (let e = 0; e < 4; e++) for (let y = 0; y < 3; y++)
  for (let m = 0; m < 6; m++) for (let d = 0; d < 3; d++) {
    if (!w && !e && !y && !m && !d) continue;
    push(locale, [w, e, y, m, d, 0, 0, 0, 0, 0, 0]);
  }
  for (let h = 0; h < 3; h++) for (let mi = 0; mi < 3; mi++) for (let s = 0; s < 3; s++) {
    if (!h && !mi && !s) continue;
    for (let c = 0; c < (h ? 4 : 1); c++) push(locale, [0, 0, 0, 0, 0, h, mi, s, h ? c + 1 : 0, 0, 0]);
  }
  // Combined cases: every month width against every time shape, which is what
  // selects the glue, plus the style shorthands.
  for (let m = 0; m < 6; m++) for (let w = 0; w < 2; w++)
  for (let h = 1; h < 3; h++) for (let mi = 0; mi < 3; mi++) for (let s = 0; s < 3; s++) {
    push(locale, [w ? 2 : 0, 0, 1, m, 1, h, mi, s, 0, 0, 0]);
  }
  for (let ds = 0; ds < 5; ds++) for (let ts = 0; ts < 5; ts++) {
    if (!ds && !ts) continue;
    push(locale, [0, 0, 0, 0, 0, 0, 0, 0, 0, ds, ts]);
  }
}
const esc = s => JSON.stringify(s);
let out = `/*
 * Generated by scripts/gen_intl_datetime_vectors.mjs. Each row carries a locale
 * index, the field width ordinals the harness rebuilds an option bag from, a
 * time value, and the text the reference ECMA-402 implementation renders.
 * Trailing zero ordinals are dropped, so a row stops at its last named field.
 */
globalThis.__intlDateTimeLocales = ${JSON.stringify(locales)};
globalThis.__intlDateTimeVectors = [
`;
for (const [l, c, t, text] of vectors) out += `[${l},[${c.join(',')}],${t},${esc(text)}],\n`;
out += `];\n`;
process.stdout.write(out);
console.error('vectors', vectors.length);
